#!/bin/sh

set -e

TDIR=$1
MIRROR=$2
DISKNUM=$3
CDDIR=$4
ARCHES=$5

cd $CDDIR

# Rebrand Debian into Kali
sed -i -e 's|Debian GNU/Linux|Molly Eskam Linux v1.0|g' \
    -e 's|Kali GNU/Linux|Molly Eskam Linux v1.0|g' \
    -e 's|Debian kali-rolling|Molly Eskam Linux v1.0|g' \
    -e 's|Debian|Molly|g' \
    -e 's|DEBIAN|MOLLY|g' \
    ../boot$DISKNUM/isolinux/menu.cfg \
    ../boot$DISKNUM/isolinux/*.txt \
    boot/grub/theme/* \
    autorun.inf

# Replace Debian specific documentation
rm -rf css
cat >README.txt <<EOF
This disc contains an installer for Molly Eskam Linux v1.0.

Read more at: https://github.com/independentcod/MollyEskam-Linux
EOF
cat >README.html <<EOF
<html>
<head><title>Molly Eskam Linux v1.0 Installer Disc</title></head>
<body>
This disc contains an installer for Molly Eskam Linux v1.0.

Read more at: <a href="https://github.com/independentcod/MollyEskam-Linux">independentcod's GitHub Repositories</a>
</body>
</html>
EOF

# Replace kali-last-snapshot with kali-rolling
if [ -e dists/kali-last-snapshot ]; then
    mv dists/kali-last-snapshot dists/kali-rolling
    rm -f dists/stable && ln -sf kali-rolling dists/stable
    sed -i -e 's|kali-last-snapshot|kali-rolling|g' \
	dists/kali-rolling/Release
fi

# Redo the md5sum.txt due to our changes
find . -type f | grep -v ./md5sum.txt | xargs md5sum | sort -uk2 > md5sum.txt
