// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1596936419);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1596950662);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1596771493);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7daf3b84-70a0-47b3-b732-be9fcd988cfa}");
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200720181548");
user_pref("browser.slowStartup.averageTime", 4659);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20200720181548");
user_pref("browser.startup.homepage_override.mstone", "68.11.0");
user_pref("browser.startup.lastColdStartupCheck", 1596950632);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.11.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200720181548");
user_pref("extensions.lastAppVersion", "68.11.0");
user_pref("extensions.lastPlatformVersion", "68.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"c0e8e9aa-fa46-44c0-b6fd-7b045b09fc52\",\"fxmonitor@mozilla.org\":\"a1dd42ac-ed75-48bb-ac69-5e43d7415fab\",\"screenshots@mozilla.org\":\"10c9e4dc-a434-4429-afcf-e8c9561c762f\",\"webcompat-reporter@mozilla.org\":\"0062f487-5f06-40ef-9547-e999fd81634a\",\"webcompat@mozilla.org\":\"66f606e5-be43-4bb5-ab0e-bb25352c880b\",\"default-theme@mozilla.org\":\"5e22aafd-212b-4910-a446-5edb5e9e9300\",\"google@search.mozilla.org\":\"ddc69e78-d41a-4648-af2e-fd1252dc1b93\",\"amazondotcom@search.mozilla.org\":\"f1a9a167-2dbe-44d9-9a0d-c79e5d453c9d\",\"bing@search.mozilla.org\":\"3fdad985-ab7e-4bdc-8fd8-becf5aaf5231\",\"ddg@search.mozilla.org\":\"ba5c62b4-00ab-4537-99c5-2e4027248c40\",\"ebay@search.mozilla.org\":\"1f4a7219-26c0-4ad2-b526-7bbe6122498a\",\"twitter@search.mozilla.org\":\"97992fbc-adbb-4af6-9ccb-408bb8f296f7\",\"wikipedia@search.mozilla.org\":\"d4b60ea4-e417-4b68-8bd6-a82750502f03\"}");
user_pref("media.gmp-manager.buildID", "20200720181548");
user_pref("media.gmp-manager.lastCheck", 1596936435);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "78889cf9-78d0-4465-9290-391e91d2fff0");
user_pref("security.sandbox.plugin.tempDirSuffix", "77255135-f5d9-4656-85ea-9cd085941b8c");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1596950631);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200720181548");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
