#!/bin/bash
echo "Updating your distribution please do not close this window until operation complete.";
bash -c "apt update && apt full-upgrade -y && apt install kali-linux-nethunter -y && apt autoremove -y";
