// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1598698126);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1598698246);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1598698366);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 7140);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1598698096);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{530bb80c-dd27-4bdc-806d-09d4f563acfc}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1598698141027");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1598699951027");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1598698116088");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1598701716088");
user_pref("browser.search.cohort", "nov17-2");
user_pref("browser.search.region", "CA");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.slowStartup.averageTime", 17563);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "https://independentcod.github.io | https://duckduckgo.com");
user_pref("browser.startup.homepage_override.buildID", "20200720181548");
user_pref("browser.startup.homepage_override.mstone", "68.11.0");
user_pref("browser.startup.lastColdStartupCheck", 1598698105);
user_pref("browser.startup.page", 3);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"firefoxcolor_mozilla_com-browser-action\",\"jid1-zadieub7xozojw_jetpack-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"firefoxcolor_mozilla_com-browser-action\",\"jid1-zadieub7xozojw_jetpack-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.11.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.11.0");
user_pref("extensions.lastPlatformVersion", "68.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.FirefoxColor@mozilla.com", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-ZAdIEUB7XOzOJw@jetpack", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"b52733a2-ccdf-42d1-8873-c1e60ca3c0ee\",\"fxmonitor@mozilla.org\":\"d0ad2636-38da-44ca-a0f2-e0ff118f5f78\",\"screenshots@mozilla.org\":\"ee7ced16-85db-4c86-923b-44b7a14f7edd\",\"webcompat-reporter@mozilla.org\":\"95b866a4-a6be-480f-b20c-4ffca0f51fad\",\"webcompat@mozilla.org\":\"df41c661-49e9-417d-b5e7-82141a2e011f\",\"default-theme@mozilla.org\":\"52903980-4ed1-4d9a-b1ac-3199ab8644bf\",\"google@search.mozilla.org\":\"a6c51d1f-02c6-42b4-9c44-3cbc3da4b7e2\",\"amazondotcom@search.mozilla.org\":\"2a6db3bf-ef0c-4a0c-9c8a-773762d6c921\",\"bing@search.mozilla.org\":\"87acc633-ced2-4283-a57b-3940aa8ab20e\",\"ddg@search.mozilla.org\":\"42f3654f-6418-4bbd-b4f3-0c5996476cf8\",\"ebay@search.mozilla.org\":\"7a97b07c-0331-4ea2-bdcf-5024b9abf9e2\",\"twitter@search.mozilla.org\":\"206971c5-66bc-49dd-a27a-59b88dcf82eb\",\"wikipedia@search.mozilla.org\":\"f79dc6c9-6cf2-4d73-956b-459bc643912c\",\"FirefoxColor@mozilla.com\":\"02e88b06-967d-4f0a-9578-3039fcb859a2\",\"jid1-ZAdIEUB7XOzOJw@jetpack\":\"ff661a6a-a057-46c1-aaee-1ed1057e8240\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 58998);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.general.disable_button.default_browser", false);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "4d27d972-a599-474d-acf0-ba5d341cba67");
user_pref("security.sandbox.plugin.tempDirSuffix", "f911ec0f-418e-482c-8859-b5f5242e4ec4");
user_pref("services.blocklist.pinning.checked", 1598712795);
user_pref("services.settings.clock_skew_seconds", -14429);
user_pref("services.settings.last_etag", "\"1598659285142\"");
user_pref("services.settings.last_update_seconds", 1598712795);
user_pref("services.settings.main.cfr-fxa.last_check", 1598712795);
user_pref("services.settings.main.cfr.last_check", 1598712795);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1598712795);
user_pref("services.settings.main.hijack-blocklists.last_check", 1598712795);
user_pref("services.settings.main.language-dictionaries.last_check", 1598712795);
user_pref("services.settings.main.sites-classification.last_check", 1598712795);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1598712795);
user_pref("services.settings.security.onecrl.checked", 1598712795);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1598698088);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200720181548");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
